aggregator:
  renderer: 
    latest_days: 30

  collector:
    feeds:
    - title: feeding the monkey
      url: https://monkeyseemonkeykill.wordpress.com/
      feed: https://monkeyseemonkeykill.wordpress.com/feed/
      last_read: 1604225582
    - title: tech something
      url: http://feeds.twit.tv/twit.xml
      feed: http://feeds.twit.tv/twit.xml
      last_read: 1604855629
    - title: NOA Alerts
      url: https://alerts.weather.gov/cap/al.php?x=0
      feed: https://alerts.weather.gov/cap/al.php?x=0
      last_read: 1605332161
    - title: NASA RSS
      url: https://www.nasa.gov/content/nasa-rss-feeds
      feed: https://www.nasa.gov/rss/dyn/breaking_news.rss
      last_read: 1605313320
