aggregator:
        collector:
                feeds:
                        - title: "feeding the monkey"
                          url: "https://monkeyseemonkeykill.wordpress.com/"
                          feed: "https://monkeyseemonkeykill.wordpress.com/feed/"

                        - title: "tech something"
                          url: "http://feeds.twit.tv/twit.xml"
                          feed: "http://feeds.twit.tv/twit.xml"

                        - title: "NOA Alerts"
                          url: "https://alerts.weather.gov/cap/al.php?x=0"
                          feed: "https://alerts.weather.gov/cap/al.php?x=0"

                        - title: "NASA RSS"
                          url: "https://www.nasa.gov/content/nasa-rss-feeds"
                          feed: "https://www.nasa.gov/rss/dyn/breaking_news.rss"


